### ISSUE TITLE
Taxodium URL

### ISSUE THREAD

**Issue by theosanderson** [jmcbroome/introduction-website#1]
Super cool work!

Can I suggest you change the URL (no rush at all) to point to http://taxodium.org which is intended to be the home of the generic tree viewer. I might break cov2tree.org for you at some point (but no time soon, don't panic).

(... and actually... the safest URL is https://taxonium.org/ [s/d/n/] because I plan to rebrand to avoid confusion with the actual tree species - how absurd :P )

**Comment by jmcbroome** [comment]
Thanks Theo! Your viewer is critical to making this work cleanly, and I greatly appreciate it. Thank you for the heads up on changing the URL- that's a straightforward swap that I can make whenever. Just to check, there would be no functional problem with changing from cov2tree to taxonium for link generation today?

**Comment by theosanderson** [comment]
Confirmed :)

**Comment by theosanderson** [comment]
Thanks!
